### ISSUE TITLE
Containerise the app!

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/pythainlp-webdemo#2]
Related  to https://github.com/PyThaiNLP/pythainlp/issues/88

**Comment by wannaphongcom** [comment]
ขึ้นระบบ web demo แล้วนะครับ https://pythainlp-webdemo.herokuapp.com/word_tokenizer

**Comment by heytitle** [comment]
can we close this?

**Comment by wannaphongcom** [comment]
@heytitle ok.
